### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isLazyTypeFunc')

### ISSUE THREAD

**Issue by WonderPanda** [risen228/nestjs-zod#12]
Hey I'm pretty stoked about the direction that this library is headed so I thought I'd pop it into our application tonight and see if would possibly give me a path to move away from Class-Transformer and Class-Validator on the backend.

We already have a fair number of endpoints and functionality in the app that heavily uses all the @nestjs/swagger functionality so that we can generate a type safe client to talk to the API from our frontend.

My versions are:
@nestjs/swagger `5.2.1`
@nestjs/{common/core} `8.4.7`

I'm invoking `patchNestJsSwagger();` near the top of my `main.ts` file which seems to be what the doc suggests.

When I boot up the app I get the following stack trace:
```
/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:89
        if (this.isLazyTypeFunc(type)) {
                 ^
TypeError: Cannot read properties of undefined (reading 'isLazyTypeFunc')
    at exploreModelSchema (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:89:18)
    at SchemaObjectFactory.e.exploreModelSchema (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/nestjs-zod/dist/index.js:1:13822)
    at /home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:33:36
    at Array.map (<anonymous>)
    at SchemaObjectFactory.createFromModel (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:20:45)
    at exploreApiParametersMetadata (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js:33:55)
    at /home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/swagger-explorer.js:72:45
    at Array.reduce (<anonymous>)
    at /home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/swagger-explorer.js:71:99
    at /home/jesse/code/work/circadian-risk/project-ember-web/node_modules/lodash/lodash.js:13469:38
    at /home/jesse/code/work/circadian-risk/project-ember-web/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/lodash/lodash.js:13468:7)
    at MapIterator.iteratee (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/@nestjs/swagger/dist/swagger-explorer.js:71:45)
    at MapIterator.next (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/iterare/src/map.ts:9:39)
    at FilterIterator.next (/home/jesse/code/work/circadian-risk/project-ember-web/node_modules/iterare/src/filter.ts:11:34)
```

Curious if you have any top of mind thoughts for whats going on here if not I can try and make a minimal repro and see if the same issue can be shown outside of my work project

**Comment by vesap** [comment]
I noticed that this happens if you have DTOs with NestJs decorators (https://docs.nestjs.com/openapi/types-and-parameters). Removing them and only having DTO's defined with zod functions makes the error go away.

**Comment by risenforces** [comment]
Will be fixed in https://github.com/risenforces/nestjs-zod/pull/18

**Comment by risenforces** [comment]
Please check out this answer: https://github.com/risenforces/nestjs-zod/issues/28#issuecomment-1493339203

**Comment by imranbarbhuiya** [comment]
It's not working for me and I'm not using `PartialType` but since my backend is huge, I'm migrating dto's 1 by 1. So I've some class dto and some zod, is it causing the issue?
